import { EditorView } from '@codemirror/view';
import { syntaxHighlighting, HighlightStyle } from '@codemirror/language';
import { tags as t } from '@lezer/highlight';

const FONT = "'JetBrains Mono', ui-monospace, monospace";

function withPanelOpacity(color) {
    if (!color || color === 'transparent') return color;
    return `color-mix(in oklab, ${color} calc(var(--editor-panel-opacity, 0.95) * 100%), transparent)`;
}

function buildExtensions(p) {
    const theme = EditorView.theme({
        '&': {
            color: p.fg,
            backgroundColor: withPanelOpacity(p.bg),
            height: '100%',
        },
        '.cm-content': {
            caretColor: p.caret,
            fontFamily: FONT,
            fontFeatureSettings: '"calt", "ss01", "ss02", "tnum"',
            padding: '20px 8px',
        },
        '.cm-cursor, .cm-dropCursor': {
            borderLeftColor: p.caret,
            borderLeftWidth: '1.5px',
        },
        '&.cm-focused .cm-cursor': { borderLeftColor: p.caret },
        '.cm-line': { padding: '0 4px' },
        '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, ::selection': {
            backgroundColor: p.selection,
        },
        '.cm-activeLine': { backgroundColor: p.activeLine },
        '.cm-activeLineGutter': {
            backgroundColor: 'transparent',
            color: p.accent,
        },
        '.cm-gutters': {
            backgroundColor: 'transparent',
            color: p.gutterFg,
            border: 'none',
            borderRight: `1px solid ${p.rule}`,
            fontFamily: FONT,
            fontSize: '11px',
            fontWeight: '300',
        },
        '.cm-lineNumbers .cm-gutterElement': {
            padding: '0 12px 0 18px',
            minWidth: '36px',
            fontVariantNumeric: 'tabular-nums oldstyle-nums',
            letterSpacing: '0.02em',
        },
        '.cm-foldGutter .cm-gutterElement': { color: p.gutterFg, padding: '0 4px' },
        '.cm-scroller': {
            fontFamily: FONT,
            lineHeight: '1.6',
        },
        '.cm-tooltip': {
            backgroundColor: p.tooltipBg,
            border: `1px solid ${p.rule}`,
            color: p.fg,
            fontFamily: FONT,
        },
        '.cm-tooltip.cm-tooltip-autocomplete > ul > li': { padding: '4px 10px' },
        '.cm-tooltip-autocomplete ul li[aria-selected]': {
            backgroundColor: p.selectionDim,
            color: p.fg,
        },
        '.cm-matchingBracket, &.cm-focused .cm-matchingBracket': {
            backgroundColor: 'transparent',
            outline: `1px solid ${p.accentDim}`,
            color: p.fg,
        },
        '.cm-searchMatch': { backgroundColor: p.searchMatch },
        '.cm-searchMatch.cm-searchMatch-selected': { backgroundColor: p.searchMatchSel },
        '.cm-panels': {
            backgroundColor: p.panelBg,
            color: p.fg,
            borderTop: `1px solid ${p.rule}`,
        },
        '.cm-panel input': {
            backgroundColor: 'transparent',
            color: p.fg,
            border: `1px solid ${p.rule}`,
            fontFamily: FONT,
        },
    }, { dark: p.dark !== false });

    const s = p.syntax;
    const highlight = HighlightStyle.define([
        { tag: t.comment, color: s.comment, fontStyle: 'italic' },
        { tag: t.lineComment, color: s.comment, fontStyle: 'italic' },
        { tag: t.blockComment, color: s.comment, fontStyle: 'italic' },
        { tag: t.meta, color: s.meta, fontWeight: '500' },
        { tag: t.processingInstruction, color: s.meta, fontWeight: '500' },
        { tag: t.keyword, color: s.keyword, fontWeight: s.keywordWeight || '600' },
        { tag: t.controlKeyword, color: s.keyword, fontWeight: s.keywordWeight || '600' },
        { tag: t.operatorKeyword, color: s.keyword, fontWeight: s.keywordWeight || '600' },
        { tag: t.modifier, color: s.keyword, fontWeight: s.keywordWeight || '600' },
        { tag: t.typeName, color: s.type, fontWeight: '500' },
        { tag: t.standard(t.variableName), color: s.variableSpecial, fontStyle: 'italic' },
        { tag: t.function(t.variableName), color: s.function },
        { tag: t.atom, color: s.atom, fontWeight: '500' },
        { tag: t.bool, color: s.atom, fontWeight: '500' },
        { tag: t.number, color: s.number },
        { tag: t.integer, color: s.number },
        { tag: t.float, color: s.number },
        { tag: t.string, color: s.string },
        { tag: t.operator, color: s.operator },
        { tag: t.punctuation, color: s.operator },
        { tag: t.bracket, color: s.operator },
        { tag: t.variableName, color: s.variable },
        { tag: t.propertyName, color: s.variable },
        { tag: t.invalid, color: s.invalid, textDecoration: 'underline wavy' },
    ]);

    return [theme, syntaxHighlighting(highlight)];
}

const PALETTES = {
    'almanac': {
        bg: 'transparent',
        fg: '#e8dcc1',
        caret: '#d9532a',
        selection: 'rgba(217, 83, 42, 0.22)',
        selectionDim: 'rgba(217, 83, 42, 0.18)',
        activeLine: 'rgba(232, 220, 193, 0.025)',
        gutterFg: '#74684f',
        rule: '#3a3122',
        accent: '#d9532a',
        accentDim: '#a8401f',
        tooltipBg: '#16120c',
        panelBg: '#15110a',
        searchMatch: 'rgba(199, 155, 63, 0.25)',
        searchMatchSel: 'rgba(217, 83, 42, 0.35)',
        syntax: {
            comment: '#74684f',
            meta: '#d9532a',
            keyword: '#e8dcc1',
            type: '#e8dcc1',
            variable: '#e8dcc1',
            variableSpecial: '#a89779',
            function: '#e8dcc1',
            atom: '#c79b3f',
            number: '#a8401f',
            string: '#c79b3f',
            operator: '#a89779',
            invalid: '#d9532a',
        },
    },
    'solarized-dark': {
        bg: '#002b36',
        fg: '#839496',
        caret: '#93a1a1',
        selection: '#073642',
        selectionDim: 'rgba(7, 54, 66, 0.7)',
        activeLine: 'rgba(7, 54, 66, 0.5)',
        gutterFg: '#586e75',
        rule: '#073642',
        accent: '#268bd2',
        accentDim: '#2aa198',
        tooltipBg: '#073642',
        panelBg: '#073642',
        searchMatch: 'rgba(181, 137, 0, 0.35)',
        searchMatchSel: 'rgba(203, 75, 22, 0.45)',
        syntax: {
            comment: '#586e75',
            meta: '#cb4b16',
            keyword: '#859900',
            type: '#b58900',
            variable: '#839496',
            variableSpecial: '#93a1a1',
            function: '#268bd2',
            atom: '#2aa198',
            number: '#d33682',
            string: '#2aa198',
            operator: '#586e75',
            invalid: '#dc322f',
        },
    },
    'solarized-light': {
        dark: false,
        bg: '#fdf6e3',
        fg: '#657b83',
        caret: '#586e75',
        selection: '#eee8d5',
        selectionDim: 'rgba(238, 232, 213, 0.7)',
        activeLine: 'rgba(238, 232, 213, 0.55)',
        gutterFg: '#93a1a1',
        rule: '#eee8d5',
        accent: '#268bd2',
        accentDim: '#2aa198',
        tooltipBg: '#fdf6e3',
        panelBg: '#eee8d5',
        searchMatch: 'rgba(181, 137, 0, 0.30)',
        searchMatchSel: 'rgba(203, 75, 22, 0.40)',
        syntax: {
            comment: '#93a1a1',
            meta: '#cb4b16',
            keyword: '#859900',
            type: '#b58900',
            variable: '#657b83',
            variableSpecial: '#586e75',
            function: '#268bd2',
            atom: '#2aa198',
            number: '#d33682',
            string: '#2aa198',
            operator: '#93a1a1',
            invalid: '#dc322f',
        },
    },
    'dracula': {
        bg: '#282a36',
        fg: '#f8f8f2',
        caret: '#f8f8f0',
        selection: '#44475a',
        selectionDim: 'rgba(68, 71, 90, 0.7)',
        activeLine: '#2f3140',
        gutterFg: '#6272a4',
        rule: '#44475a',
        accent: '#ff79c6',
        accentDim: '#bd93f9',
        tooltipBg: '#21222c',
        panelBg: '#21222c',
        searchMatch: 'rgba(241, 250, 140, 0.30)',
        searchMatchSel: 'rgba(255, 121, 198, 0.40)',
        syntax: {
            comment: '#6272a4',
            meta: '#ffb86c',
            keyword: '#ff79c6',
            type: '#8be9fd',
            variable: '#f8f8f2',
            variableSpecial: '#bd93f9',
            function: '#50fa7b',
            atom: '#bd93f9',
            number: '#bd93f9',
            string: '#f1fa8c',
            operator: '#ff79c6',
            invalid: '#ff5555',
        },
    },
    'monokai': {
        bg: '#272822',
        fg: '#f8f8f2',
        caret: '#f8f8f0',
        selection: '#49483e',
        selectionDim: 'rgba(73, 72, 62, 0.7)',
        activeLine: '#3e3d32',
        gutterFg: '#90908a',
        rule: '#49483e',
        accent: '#f92672',
        accentDim: '#a6e22e',
        tooltipBg: '#1e1f1a',
        panelBg: '#1e1f1a',
        searchMatch: 'rgba(230, 219, 116, 0.30)',
        searchMatchSel: 'rgba(249, 38, 114, 0.40)',
        syntax: {
            comment: '#75715e',
            meta: '#f92672',
            keyword: '#f92672',
            type: '#66d9ef',
            variable: '#f8f8f2',
            variableSpecial: '#fd971f',
            function: '#a6e22e',
            atom: '#ae81ff',
            number: '#ae81ff',
            string: '#e6db74',
            operator: '#f92672',
            invalid: '#f92672',
        },
    },
    'one-dark': {
        bg: '#282c34',
        fg: '#abb2bf',
        caret: '#528bff',
        selection: '#3e4451',
        selectionDim: 'rgba(62, 68, 81, 0.7)',
        activeLine: '#2c313c',
        gutterFg: '#636d83',
        rule: '#3e4451',
        accent: '#528bff',
        accentDim: '#c678dd',
        tooltipBg: '#21252b',
        panelBg: '#21252b',
        searchMatch: 'rgba(229, 192, 123, 0.30)',
        searchMatchSel: 'rgba(82, 139, 255, 0.40)',
        syntax: {
            comment: '#5c6370',
            meta: '#56b6c2',
            keyword: '#c678dd',
            type: '#e5c07b',
            variable: '#e06c75',
            variableSpecial: '#d19a66',
            function: '#61afef',
            atom: '#d19a66',
            number: '#d19a66',
            string: '#98c379',
            operator: '#56b6c2',
            invalid: '#e06c75',
        },
    },
    'tokyo-night': {
        bg: '#24283b',
        fg: '#c0caf5',
        caret: '#c0caf5',
        selection: '#364a82',
        selectionDim: 'rgba(54, 74, 130, 0.7)',
        activeLine: '#292e42',
        gutterFg: '#3b4261',
        rule: '#292e42',
        accent: '#7aa2f7',
        accentDim: '#bb9af7',
        tooltipBg: '#1f2335',
        panelBg: '#1f2335',
        searchMatch: 'rgba(158, 206, 106, 0.30)',
        searchMatchSel: 'rgba(122, 162, 247, 0.40)',
        syntax: {
            comment: '#565f89',
            meta: '#7dcfff',
            keyword: '#bb9af7',
            type: '#2ac3de',
            variable: '#c0caf5',
            variableSpecial: '#f7768e',
            function: '#7aa2f7',
            atom: '#ff9e64',
            number: '#ff9e64',
            string: '#9ece6a',
            operator: '#89ddff',
            invalid: '#f7768e',
        },
    },
    'gruvbox-dark': {
        bg: '#282828',
        fg: '#ebdbb2',
        caret: '#ebdbb2',
        selection: '#504945',
        selectionDim: 'rgba(80, 73, 69, 0.7)',
        activeLine: '#32302f',
        gutterFg: '#928374',
        rule: '#3c3836',
        accent: '#fabd2f',
        accentDim: '#fe8019',
        tooltipBg: '#1d2021',
        panelBg: '#1d2021',
        searchMatch: 'rgba(184, 187, 38, 0.30)',
        searchMatchSel: 'rgba(250, 189, 47, 0.45)',
        syntax: {
            comment: '#928374',
            meta: '#fe8019',
            keyword: '#fb4934',
            type: '#fabd2f',
            variable: '#ebdbb2',
            variableSpecial: '#d3869b',
            function: '#8ec07c',
            atom: '#d3869b',
            number: '#d3869b',
            string: '#b8bb26',
            operator: '#fe8019',
            invalid: '#fb4934',
        },
    },
};

export const THEME_LIST = [
    { id: 'almanac',         name: 'Almanac (default)' },
    { id: 'solarized-dark',  name: 'Solarized Dark' },
    { id: 'solarized-light', name: 'Solarized Light' },
    { id: 'dracula',         name: 'Dracula' },
    { id: 'monokai',         name: 'Monokai' },
    { id: 'one-dark',        name: 'One Dark' },
    { id: 'tokyo-night',     name: 'Tokyo Night' },
    { id: 'gruvbox-dark',    name: 'Gruvbox Dark' },
];

export const DEFAULT_THEME = 'almanac';

const cache = new Map();

export function getThemeExtensions(id) {
    const themeId = PALETTES[id] ? id : DEFAULT_THEME;
    if (cache.has(themeId)) return cache.get(themeId);
    const ext = buildExtensions(PALETTES[themeId]);
    cache.set(themeId, ext);
    return ext;
}
